DECISION_GUIDANCE = {
    1: {
        "confidence": "MÉDIA",
        "interpretation": "Há uma tarifa padrão de ônibus para Alagoinha e uma segunda anotação de moto táxi ligada a 'Daiane'. A exceção não deve substituir a tarifa padrão sem confirmação.",
        "context_rows": [
            {"sheet": "VALORES DE PASSAGEM", "row": 11, "label": "Tarifa padrão encontrada", "text": "ALAGOINHA | BA | R$ 4,60 | Gasolina 6,53 (25/07/26)"},
            {"sheet": "VALORES DE PASSAGEM", "row": 12, "label": "Exceção/dúvida", "text": "ALAGOINHA | BA | R$ 6,00 | moto taxi Daiane ??"},
        ],
        "open_questions": ["Quem é 'Daiane' e a exceção de R$ 6,00 vale só para ela?", "O R$ 6,00 é por trecho de moto táxi ou outro critério?", "Qual a vigência da exceção?"],
        "rule_kind": "TARIFA",
        "scope": "Alagoinha/BA",
        "options": [
            {"label": "Tarifa padrão", "value": "4,60", "modal": "Ônibus", "condition": "Tarifa municipal padrão"},
            {"label": "Exceção", "value": "6,00", "modal": "Moto táxi", "condition": "Associada a 'Daiane' — confirmar escopo"},
        ],
        "notes": "Sugestão gerada a partir das linhas 11 e 12. Confirmar a exceção antes de homologar.",
    },
    2: {
        "confidence": "MÉDIA",
        "interpretation": "A planilha apresenta R$ 5,20 como primeiro valor e R$ 5,80 associado a 'Davi Linhares'. O segundo parece uma exceção individual, mas o motivo não está registrado.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 14, "label": "Registro", "text": "CAMAÇARI | BA | R$ 5,20 - (R$ 5,80 Davi Linhares) | Gasolina 5,94"}],
        "open_questions": ["O R$ 5,80 vale somente para Davi Linhares?", "Qual o motivo/modal/trajeto da diferença?", "A tarifa padrão vigente é R$ 5,20?"],
        "rule_kind": "TARIFA",
        "scope": "Camaçari/BA",
        "options": [
            {"label": "Tarifa padrão", "value": "5,20", "modal": "Ônibus", "condition": "Condição geral — confirmar"},
            {"label": "Exceção", "value": "5,80", "condition": "Davi Linhares — confirmar motivo e escopo"},
        ],
    },
    3: {
        "confidence": "ALTA",
        "interpretation": "O próprio texto diferencia o pagamento com Cartão BEM do pagamento em dinheiro. Existe ainda outra anotação, em OBSERVAÇÕES, dizendo que Vitória da Conquista 'não tem integração'.",
        "context_rows": [
            {"sheet": "VALORES DE PASSAGEM", "row": 29, "label": "Tarifa", "text": "Vitória da Conquista | R$ 4,00 com Cartão BEM | R$ 4,50 em dinheiro"},
            {"sheet": "OBSERVAÇÕES", "row": 107, "label": "Regra relacionada", "text": "VITÓRIA DA CONQUISTA | NÃO TEM INTEGRAÇÃO"},
        ],
        "open_questions": ["Desde quando os valores R$ 4,00/R$ 4,50 estão vigentes?", "A ausência de integração vale para todas as linhas/colaboradores?"],
        "rule_kind": "TARIFA_POR_PAGAMENTO",
        "scope": "Vitória da Conquista/BA",
        "options": [
            {"label": "Cartão BEM", "value": "4,00", "modal": "Ônibus", "condition": "Pagamento com Cartão BEM"},
            {"label": "Dinheiro", "value": "4,50", "modal": "Ônibus", "condition": "Pagamento em dinheiro"},
        ],
    },
    4: {
        "confidence": "BAIXA",
        "interpretation": "Há dois valores, mas a planilha não informa qual condição corresponde a cada um.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 38, "label": "Registro", "text": "TEIXEIRA DE FREITAS | BA | R$ 3,70 - R$ 4,10"}],
        "open_questions": ["Qual situação usa R$ 3,70?", "Qual situação usa R$ 4,10?", "Qual deles é a tarifa padrão vigente?"],
        "rule_kind": "TARIFA",
        "scope": "Teixeira de Freitas/BA",
        "options": [
            {"label": "Valor 1", "value": "3,70", "modal": "Ônibus", "condition": ""},
            {"label": "Valor 2", "value": "4,10", "modal": "Ônibus", "condition": ""},
        ],
    },
    5: {
        "confidence": "MÉDIA",
        "interpretation": "R$ 4,80 está explicitamente marcado como 'dentro'. A condição de R$ 4,95 não está descrita.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 42, "label": "Registro", "text": "EUSÉBIO | CE | R$ 4,95 - R$ 4,80 (dentro)"}],
        "open_questions": ["R$ 4,80 significa dentro do município?", "R$ 4,95 é metropolitano ou outra condição?"],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Eusébio/CE",
        "options": [
            {"label": "Dentro", "value": "4,80", "modal": "Ônibus", "condition": "Dentro — confirmar se é dentro do município"},
            {"label": "Outro trajeto", "value": "4,95", "modal": "Ônibus", "condition": "Condição não informada"},
        ],
    },
    6: {
        "confidence": "ALTA",
        "interpretation": "A planilha diferencia explicitamente tarifa metropolitana e tarifa dentro do município.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 43, "label": "Registro", "text": "MARACANAÚ | CE | metropolitano R$ 5,95 | R$ 3,67 dentro município"}],
        "open_questions": ["Confirmar a vigência dos dois valores."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Maracanaú/CE",
        "options": [
            {"label": "Metropolitano", "value": "5,95", "modal": "Ônibus", "condition": "Trajeto metropolitano"},
            {"label": "Municipal", "value": "3,67", "modal": "Ônibus", "condition": "Dentro do município"},
        ],
    },
    7: {
        "confidence": "MÉDIA",
        "interpretation": "R$ 8,15 está marcado como metropolitano. A condição de R$ 2,15 não foi escrita.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 45, "label": "Registro", "text": "MARANGUAPE | CE | R$ 2,15 | R$ 8,15 (metropolitano)"}],
        "open_questions": ["Qual condição usa R$ 2,15?", "Confirmar vigência."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Maranguape/CE",
        "options": [
            {"label": "Valor local", "value": "2,15", "modal": "Ônibus", "condition": "Condição não informada"},
            {"label": "Metropolitano", "value": "8,15", "modal": "Ônibus", "condition": "Trajeto metropolitano"},
        ],
    },
    8: {
        "confidence": "BAIXA",
        "interpretation": "A localidade está agrupada como Aracati/Beberibe e há dois valores sem indicação de qual pertence a qual trajeto.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 47, "label": "Registro", "text": "ARACATI/ BEBERIBE | CE | R$ 6,00 - R$ 18,00"}],
        "open_questions": ["Qual origem/destino corresponde a R$ 6,00?", "Qual origem/destino corresponde a R$ 18,00?"],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Aracati/Beberibe - CE",
        "options": [
            {"label": "Trajeto 1", "value": "6,00", "modal": "Ônibus"},
            {"label": "Trajeto 2", "value": "18,00", "modal": "Ônibus"},
        ],
    },
    9: {
        "confidence": "MÉDIA",
        "interpretation": "O texto explica parte dos valores: R$ 5,00 dentro da região e R$ 9,50 de Itapipoca para Amontada a partir de 04/06/2025. Também cita R$ 8,00 casa→loja. O valor R$ 16,00 permanece sem condição identificada.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 57, "label": "Registro", "text": "ITAPIPOCA / TRAIRI / AMONTADA | R$ 5,00 - R$ 16,00 - R$ 9,50 | Itapipoca→Amontada a partir de 04/06/25 = R$ 9,50; casa do promotor→loja = R$ 8,00; dentro da região = R$ 5,00"}],
        "open_questions": ["A que trajeto corresponde R$ 16,00?", "R$ 8,00 casa→loja ainda é uma regra válida?", "As regras valem para todos ou para colaborador específico?"],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Itapipoca/Trairi/Amontada - CE",
        "options": [
            {"label": "Dentro da região", "value": "5,00", "modal": "Ônibus", "condition": "Dentro da região"},
            {"label": "Itapipoca → Amontada", "value": "9,50", "modal": "Ônibus", "origin": "Itapipoca", "destination": "Amontada", "condition": "Alteração registrada", "valid_from": "2025-06-04"},
            {"label": "Valor sem condição", "value": "16,00", "modal": "Ônibus", "condition": "Condição não informada"},
            {"label": "Casa → loja (citado na observação)", "value": "8,00", "condition": "Casa do promotor para a loja — confirmar se ainda vale"},
        ],
    },
    10: {
        "confidence": "ALTA",
        "interpretation": "A planilha identifica R$ 5,00 dentro de Quixeramobim e dois valores para ida a Quixadá, diferenciados por operador/modal: Guanabara e Topic.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 58, "label": "Registro", "text": "QUIXERAMOBIM/QUIXADÁ | R$ 5,00 dentro Quixeramobim | R$ 10,00 Guanabara | R$ 11,50 Topic / ida a Quixadá"}],
        "open_questions": ["Confirmar se R$ 10,00 e R$ 11,50 são valores por trecho e a mesma vigência."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Quixeramobim/Quixadá - CE",
        "options": [
            {"label": "Dentro de Quixeramobim", "value": "5,00", "modal": "Ônibus", "condition": "Dentro de Quixeramobim"},
            {"label": "Quixadá - Guanabara", "value": "10,00", "modal": "Guanabara", "destination": "Quixadá", "condition": "Ida a Quixadá"},
            {"label": "Quixadá - Topic", "value": "11,50", "modal": "Topic", "destination": "Quixadá", "condition": "Ida a Quixadá"},
        ],
    },
    11: {
        "confidence": "BAIXA",
        "interpretation": "Existem dois valores para a localidade agrupada Acaraú/Preá, mas a correspondência entre local/trecho e valor não está descrita.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 62, "label": "Registro", "text": "ACARAÚ/PREÁ | CE | R$ 7,00 - R$ 5,00"}],
        "open_questions": ["Qual trecho usa R$ 7,00?", "Qual trecho usa R$ 5,00?"],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Acaraú/Preá - CE",
        "options": [
            {"label": "Valor 1", "value": "7,00", "modal": "Ônibus"},
            {"label": "Valor 2", "value": "5,00", "modal": "Ônibus"},
        ],
    },
    12: {
        "confidence": "BAIXA",
        "interpretation": "Há três valores e três referências de localidade/PDV, porém a planilha não indica a correspondência entre cada valor e cada trajeto.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 69, "label": "Registro", "text": "PACAJUS/HORIZONTE/MERCADÃO TEND TUDO (R. Ivaney Bandeira, 96) | R$ 5,00 - R$ 4,80 - R$ 5,80"}],
        "open_questions": ["Mapear R$ 5,00, R$ 4,80 e R$ 5,80 para as respectivas condições/origens/destinos."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Pacajus/Horizonte - CE",
        "options": [
            {"label": "Valor 1", "value": "5,00", "modal": "Ônibus"},
            {"label": "Valor 2", "value": "4,80", "modal": "Ônibus"},
            {"label": "Valor 3", "value": "5,80", "modal": "Ônibus"},
        ],
    },
    13: {
        "confidence": "BAIXA",
        "interpretation": "Horizonte possui dois valores sem descrição de condição. A linha imediatamente anterior também cita Horizonte dentro de uma regra composta, por isso não é seguro escolher automaticamente.",
        "context_rows": [
            {"sheet": "VALORES DE PASSAGEM", "row": 69, "label": "Linha relacionada", "text": "PACAJUS/HORIZONTE/MERCADÃO TEND TUDO | R$ 5,00 - R$ 4,80 - R$ 5,80"},
            {"sheet": "VALORES DE PASSAGEM", "row": 70, "label": "Registro", "text": "HORIZONTE | CE | R$ 4,80 - R$ 5,79"},
        ],
        "open_questions": ["Qual condição utiliza R$ 4,80?", "Qual condição utiliza R$ 5,79?", "R$ 5,79 substituiu algum valor anterior?"],
        "rule_kind": "TARIFA",
        "scope": "Horizonte/CE",
        "options": [
            {"label": "Valor 1", "value": "4,80", "modal": "Ônibus"},
            {"label": "Valor 2", "value": "5,79", "modal": "Ônibus"},
        ],
    },
    14: {
        "confidence": "BAIXA",
        "interpretation": "A linha contém R$ 4,80, uma anotação 'R$ 2,80 - QS' e a frase 'dentro da região é 0800'. O significado de 'QS' e '0800' precisa ser confirmado.",
        "context_rows": [
            {"sheet": "VALORES DE PASSAGEM", "row": 80, "label": "Registro", "text": "CAUCAIA | CE | R$ 4,80 - (R$ 2,80 - QS) | dentro da região é 0800"},
            {"sheet": "VALORES DE PASSAGEM", "row": 81, "label": "Regra de trajeto já normalizada", "text": "CAUCAIA / MARACANAÚ | R$ 4,80"},
        ],
        "open_questions": ["O que significa 'QS' no valor R$ 2,80?", "'0800' significa custo zero ou outra referência?", "Qual é a regra padrão de Caucaia?"],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Caucaia/CE",
        "options": [
            {"label": "Valor geral", "value": "4,80", "modal": "Ônibus", "condition": "Condição não informada"},
            {"label": "Valor anotado como QS", "value": "2,80", "condition": "QS — significado a confirmar"},
        ],
    },
    15: {
        "confidence": "MÉDIA",
        "interpretation": "R$ 5,00 aparece como valor geral e R$ 7,00 está associado a 'Diego', sugerindo uma exceção individual sem motivo registrado.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 111, "label": "Registro", "text": "PARAUAPEBAS | PA | R$ 5,00 | R$ 7,00 Diego"}],
        "open_questions": ["R$ 7,00 vale somente para Diego?", "Qual o motivo/modal/trajeto da exceção?", "Qual a vigência?"],
        "rule_kind": "TARIFA",
        "scope": "Parauapebas/PA",
        "options": [
            {"label": "Tarifa padrão", "value": "5,00", "modal": "Ônibus", "condition": "Condição geral — confirmar"},
            {"label": "Exceção", "value": "7,00", "condition": "Diego — confirmar motivo e escopo"},
        ],
    },
    16: {
        "confidence": "ALTA",
        "interpretation": "A planilha distingue R$ 4,00 do valor de R$ 5,50 para 'interior'.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 118, "label": "Registro", "text": "MARABÁ | PA | R$ 4,00 | R$ 5,50 interior"}],
        "open_questions": ["Definir precisamente o que a empresa chama de 'interior' para esta regra.", "Confirmar vigência."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Marabá/PA",
        "options": [
            {"label": "Tarifa padrão", "value": "4,00", "modal": "Ônibus", "condition": "Área urbana/padrão — confirmar nomenclatura"},
            {"label": "Interior", "value": "5,50", "modal": "Ônibus", "condition": "Interior"},
        ],
    },
    17: {
        "confidence": "MÉDIA",
        "interpretation": "A planilha registra R$ 5,45 e R$ 2,72, mas não identifica explicitamente o segundo como integração/meia. A relação precisa ser homologada.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 125, "label": "Registro", "text": "JOÃO PESSOA | PB | R$ 5,45 (24.01) | R$ 2,72 | Gasolina 6,35"}],
        "open_questions": ["R$ 2,72 é integração, meia tarifa ou outra regra?", "O marcador '24.01' é uma data de vigência?"],
        "rule_kind": "TARIFA_POR_PAGAMENTO",
        "scope": "João Pessoa/PB",
        "options": [
            {"label": "Tarifa integral", "value": "5,45", "modal": "Ônibus", "condition": "Tarifa cheia — confirmar"},
            {"label": "Valor reduzido", "value": "2,72", "modal": "Ônibus", "condition": "Condição não informada; confirmar integração/meia"},
        ],
    },
    18: {
        "confidence": "ALTA",
        "interpretation": "A observação descreve a lógica: saída de Bayeux até o Terminal de Varadouro e, em João Pessoa, pagamento de 50%; dentro de João Pessoa a integração é 100%.",
        "context_rows": [
            {"sheet": "VALORES DE PASSAGEM", "row": 126, "label": "Bayeux", "text": "BAYEUX | R$ 5,20 | R$ 2,60 | em João Pessoa paga 50%; dentro de João Pessoa integração 100%"},
            {"sheet": "VALORES DE PASSAGEM", "row": 127, "label": "Regra semelhante", "text": "CABEDELO | R$ 5,40 | R$ 2,70 | mesma lógica de 50% em João Pessoa"},
        ],
        "open_questions": ["Confirmar se a regra se aplica a todos que fazem esse deslocamento e desde quando."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Bayeux/PB",
        "options": [
            {"label": "Bayeux → Terminal", "value": "5,20", "modal": "Ônibus", "origin": "Bayeux", "destination": "Terminal do Varadouro", "condition": "Passagem até o Terminal do Varadouro"},
            {"label": "Etapa em João Pessoa", "value": "2,60", "modal": "Ônibus", "destination": "João Pessoa", "condition": "50% do valor na etapa em João Pessoa"},
        ],
    },
    19: {
        "confidence": "ALTA",
        "interpretation": "A observação descreve a lógica de saída até o Terminal de Varadouro e pagamento de 50% em João Pessoa.",
        "context_rows": [
            {"sheet": "VALORES DE PASSAGEM", "row": 127, "label": "Cabedelo", "text": "CABEDELO | R$ 5,40 | R$ 2,70 | em João Pessoa paga 50%; dentro de João Pessoa integração 100%"},
            {"sheet": "VALORES DE PASSAGEM", "row": 128, "label": "Regra semelhante", "text": "SANTA RITA | R$ 5,40 | R$ 2,70 | nova tarifa R$ 5,60 a partir de 06/07/26"},
        ],
        "open_questions": ["Confirmar a vigência e se a regra vale para todos os colaboradores que fazem o trajeto."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Cabedelo/PB",
        "options": [
            {"label": "Cabedelo → Terminal", "value": "5,40", "modal": "Ônibus", "origin": "Cabedelo", "destination": "Terminal do Varadouro", "condition": "Passagem até o Terminal do Varadouro"},
            {"label": "Etapa em João Pessoa", "value": "2,70", "modal": "Ônibus", "destination": "João Pessoa", "condition": "50% do valor na etapa em João Pessoa"},
        ],
    },
    20: {
        "confidence": "MÉDIA",
        "interpretation": "Há tarifa histórica de R$ 5,40, valor de 50% R$ 2,70 e nova tarifa integral de R$ 5,60 a partir de 06/07/2026. A planilha não informa se o valor reduzido também mudou.",
        "context_rows": [
            {"sheet": "VALORES DE PASSAGEM", "row": 128, "label": "Santa Rita", "text": "SANTA RITA | R$ 5,40 | R$ 2,70 | R$ 5,60 a partir de 06/07/26 | em João Pessoa paga 50%"},
            {"sheet": "VALORES DE PASSAGEM", "row": 126, "label": "Lógica regional relacionada", "text": "BAYEUX | em João Pessoa paga 50%; dentro de João Pessoa integração 100%"},
        ],
        "open_questions": ["Com a tarifa cheia de R$ 5,60, o valor de 50% passou para R$ 2,80? A planilha não confirma isso.", "Confirmar se R$ 5,40/R$ 2,70 ficam apenas como histórico anterior a 06/07/26."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Santa Rita/PB",
        "options": [
            {"label": "Tarifa integral histórica", "value": "5,40", "modal": "Ônibus", "origin": "Santa Rita", "destination": "Terminal do Varadouro", "condition": "Valor anterior à alteração"},
            {"label": "50% histórico", "value": "2,70", "modal": "Ônibus", "destination": "João Pessoa", "condition": "50% na etapa em João Pessoa — confirmar vigência"},
            {"label": "Nova tarifa integral", "value": "5,60", "modal": "Ônibus", "origin": "Santa Rita", "condition": "Nova tarifa integral", "valid_from": "2026-07-06"},
        ],
    },
    21: {
        "confidence": "ALTA",
        "interpretation": "O texto informa valor antigo de R$ 4,30 e valor único de R$ 4,50 a partir de 01/02/2026. A única dúvida relevante é o escopo da localidade agrupada Cabo Santo Agostinho/Escada.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 140, "label": "Registro", "text": "CABO SANTO AGOSTINHO/ESCADA | valor antes R$ 4,30 | a partir de 01/02/26 R$ 4,50 | ÚNICO VALOR"}],
        "open_questions": ["R$ 4,50 vale igualmente para Cabo de Santo Agostinho e Escada?"],
        "rule_kind": "TARIFA",
        "scope": "Cabo de Santo Agostinho/PE e Escada/PE",
        "options": [
            {"label": "Tarifa vigente", "value": "4,50", "modal": "Ônibus", "condition": "Único valor", "valid_from": "2026-02-01"},
            {"label": "Tarifa histórica", "value": "4,30", "modal": "Ônibus", "condition": "Valor anterior a 01/02/2026"},
        ],
    },
    22: {
        "confidence": "ALTA",
        "interpretation": "A planilha registra R$ 5,00 como valor geral e R$ 6,80 para Zona Rural, citando Sabrinna da Penha.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 142, "label": "Registro", "text": "GARANHUNS | PE | R$ 5,00 | Zona Rural R$ 6,80 (Sabrinna da Penha)"}],
        "open_questions": ["R$ 6,80 vale para toda Zona Rural ou somente para Sabrinna da Penha?", "Confirmar vigência."],
        "rule_kind": "TARIFA_POR_TRAJETO",
        "scope": "Garanhuns/PE",
        "options": [
            {"label": "Tarifa padrão", "value": "5,00", "modal": "Ônibus", "condition": "Área padrão/urbana — confirmar"},
            {"label": "Zona Rural", "value": "6,80", "modal": "Ônibus", "condition": "Zona Rural; anotação cita Sabrinna da Penha"},
        ],
    },
    23: {
        "confidence": "BAIXA",
        "interpretation": "A expressão 'R$ 5,00 + 3,00' pode significar composição de duas passagens/custos, mas a planilha não explica a condição.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 157, "label": "Registro", "text": "RIBEIRÃO | PE | R$ 5,00 + R$ 3,00"}],
        "open_questions": ["Os valores devem ser somados, totalizando R$ 8,00?", "O que representa o adicional de R$ 3,00?", "Em quais dias/rotas a composição se aplica?"],
        "rule_kind": "COMPOSICAO",
        "scope": "Ribeirão/PE",
        "options": [
            {"label": "Componente 1", "value": "5,00", "condition": "Componente da composição — confirmar"},
            {"label": "Componente 2", "value": "3,00", "condition": "Adicional — confirmar motivo"},
        ],
    },
    24: {
        "confidence": "ALTA",
        "interpretation": "A planilha identifica tarifa cheia de R$ 5,00 e meia de R$ 2,50. A observação registra 'a partir de 01/04/26'.",
        "context_rows": [{"sheet": "VALORES DE PASSAGEM", "row": 167, "label": "Registro", "text": "PARNAÍBA | PI | R$ 5,00 | R$ 2,50 (meia) | 17/3 | a partir de 01/04/26"}],
        "open_questions": ["Confirmar se 01/04/2026 é a vigência dos dois valores e o que significa '17/3'."],
        "rule_kind": "TARIFA_POR_PAGAMENTO",
        "scope": "Parnaíba/PI",
        "options": [
            {"label": "Tarifa cheia", "value": "5,00", "modal": "Ônibus", "condition": "Tarifa integral", "valid_from": "2026-04-01"},
            {"label": "Meia tarifa", "value": "2,50", "modal": "Ônibus", "condition": "Meia tarifa", "valid_from": "2026-04-01"},
        ],
    },
    25: {
        "confidence": "MÉDIA",
        "interpretation": "Em OBSERVAÇÕES há um registro para Vitória da Conquista dizendo apenas 'NÃO TEM INTEGRAÇÃO'. A planilha de tarifas da mesma cidade diferencia Cartão BEM (R$ 4,00) e dinheiro (R$ 4,50).",
        "context_rows": [
            {"sheet": "OBSERVAÇÕES", "row": 107, "label": "Exceção", "text": "VITÓRIA DA CONQUISTA | BA | NÃO TEM INTEGRAÇÃO"},
            {"sheet": "VALORES DE PASSAGEM", "row": 29, "label": "Tarifa relacionada", "text": "Vitória da Conquista | R$ 4,00 Cartão BEM | R$ 4,50 dinheiro"},
        ],
        "open_questions": ["A ausência de integração vale para todas as linhas?", "Vale para todos os colaboradores?", "Qual a data inicial dessa regra?"],
        "rule_kind": "INTEGRACAO",
        "scope": "Vitória da Conquista/BA",
        "options": [
            {"label": "Integração", "condition": "Não há integração — confirmar abrangência"},
        ],
        "notes": "Esta decisão deve ser compatibilizada com a tarifa de Vitória da Conquista (decisão 3).",
    },
}
